# Generated by Django 3.2 on 2022-12-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('vaqt', models.DateTimeField(auto_now_add=True)),
                ('rasm', models.CharField(max_length=255)),
                ('tarif', models.TextField()),
            ],
        ),
    ]
