# Generated by Django 3.2 on 2022-12-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tarif',
            new_name='davomiylik',
        ),
        migrations.AddField(
            model_name='post',
            name='turi',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
