# Generated by Django 3.2 on 2022-12-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20221221_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='turi',
            new_name='turi1',
        ),
        migrations.AddField(
            model_name='post',
            name='turi2',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
